name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: docker-sfdl-bash-loader

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Build and publish Docker Image to GitHub Packages Registry
        # You may pin to the exact commit or the version.
        # uses: VaultVulp/gp-docker-action@abd86dfdcd23929f6195a0fd455769a73b7276da
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          # GitHub token to push Docker image to GitHub Packages
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          # Docker Image name
          image-name: docker-sfdl-bash-loader
          # Docker Image tag
          image-tag: latest
          # Extract git-tag from repository
          extract-git-tag: false
          # Dockerfile name
          dockerfile: Dockerfile
          # Path to build context
          build-context: .
          # Pull the image before buiding it
          pull-image: false
